[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "phoque2-workspace"
version = "0.1.0"
description = "Phoque2 development workspace"
authors = ["Timst <timst44@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.12"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
black = "^24.0.0"
isort = "^5.13.0"
mypy = "^1.8.0"
pylint = "^3.0.0"

[tool.poetry.group.build.dependencies]
poetry-core = "^2.0.0"